import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Footer from "../components/footer/Footer";
import HomeContent from "../components/HomeContent";
import Navbar from "../components/header/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Crafting Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner/>
      <HomeContent/>
    </div>
  );
}
